# Generated by Django 2.2.6 on 2019-10-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('webapp', '0002_products_discounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products_shoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoe_type', models.CharField(max_length=255)),
                ('shoe_color', models.CharField(max_length=100)),
                ('shoe_brand', models.CharField(max_length=80)),
            ],
        ),
    ]
